### ISSUE TITLE
[EPIC] Improve Cogit generated code

### ISSUE THREAD

**Issue by PalumboN** [Alamvic/druid#106]
I write here many tasks related to it. Then we can create an issue for each if necessary.

- [ ] Avoid extra moves on spilling https://github.com/pharo-project/pharo-vm/pull/736/#discussion_r1482544891
- [ ] Avoid extra move of constants (to make operations) https://github.com/pharo-project/pharo-vm/pull/736/#discussion_r1482555241 
- [ ] Improve booleans on IR https://github.com/pharo-project/pharo-vm/pull/736/#discussion_r1482545390
- [ ] Split phi functions to open the opportunity for constant folding https://github.com/pharo-project/pharo-vm/pull/736/#discussion_r1482550289 
https://github.com/Alamvic/druid/issues/104
- [ ] Why is it making the same comparison twice? https://github.com/pharo-project/pharo-vm/pull/736/#discussion_r1482551303
- [ ] Improve the generated code for better human understanding:
  - [ ] Add _enters_ to the code between basic block generation
  - [ ] Add comments to the code, based on original method selectors in the interpreter.
  - [ ] Add a comment about why a primitive is incomplete https://github.com/pharo-project/pharo-vm/pull/736/#discussion_r1482554453
- [ ] To have some heuristic of the common path for code layout https://github.com/pharo-project/pharo-vm/pull/736/#discussion_r1482559748
