### ISSUE TITLE
[Epic] MDGA: Make Druid Great Again

### ISSUE THREAD

**Issue by PalumboN** [Alamvic/druid#91]
### Bytecodes

- [ ] gen_ExtPushFullClosureBytecode
  - [ ] Allocate dynamic registers outside the loops?

- [ ] gen_PushLiteralVariable16CasesBytecode
  - [ ] Stage the access to the association but resolve the value at runtime (avoid the doble `int64AtPointer`)
  - [ ] Annotate the association

### Primitives

- ???? TODO
